apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitdata-pv-claim
  namespace: dev
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi