apiVersion : apps/v1
kind: Deployment
metadata:
  name: tmapi
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tmapi
  template:
    metadata:
      labels:
        app: tmapi 
    spec:
      containers:
        - name: xtpython
          image: xtmagento.azurecr.io/xtpython
          ports:
          - containerPort: 8000
          env:
            - name: MODE
              value: MAIN
            - name: CMD
              value: APP
